data_dir: "/home/foo"
name: "my_homebattery_remote"
secret: "a_long_random_string"
log:
  level: "INFO"
  path: "~/foo.log"
  days: 0
mqtt:
  host: ""
  ca: ""
  tls_insecure: false
  user: ""
  password: ""
homebattery:
  my_foo_controller: 
    root: "homebattery/foo"
  my_bar_controller: 
    root: "homebattery/bar"
    is_mode_settable: false
    is_resettable: false
web:
  listen: "0.0.0.0"
  port: 8080
  admin_user: "admin"
  admin_password: "my_password_hash"
  user_user: "user"
  user_password: "my_password_hash"
  keyfile: ""
  certfile: ""
energy:
  charger_efficiency_factor: 1.0
  inverter_efficiency_factor: 1.0
  minimum_margin: 0.00
  csv_file: "/path/to/file.csv"
tibber:
  token: "my_encrypted_tibber_token"